plugins {
    `java-library`
    kotlin("jvm")
    kotlin("kapt")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

dependencies {
    // Lint APIs (compileOnly)
    compileOnly(libs.lint.api)
    compileOnly(libs.lint.checks)

    // Gson for report generation
    implementation(libs.gson)

    // Auto-service for processor registration
    compileOnly(libs.auto.service.annotations)
    kapt(libs.auto.service)

    // Kotlin Standard Library
    compileOnly(kotlin("stdlib"))

    // Ensure javax annotations and tools are available
    compileOnly("javax.annotation:javax.annotation-api:1.3.2")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}

// Custom task for compliance report generation
tasks.register("generateComplianceReport") {
    group = "verification"
    description = "Generates a Markdown compliance report from the UI lint JSON output."

    doLast {
        val resultsDirStr = project.findProperty("lint.results.dir")?.toString()
            ?: "${project.layout.buildDirectory.asFile.get()}/reports"
        val reportFile = file("${resultsDirStr}/ui-lint-report.json")
        val outputFile = file("${resultsDirStr}/UI_COMPLIANCE_REPORT.md")
        val baselineFile = file("${project.findProperty("lint.baseline.dir")?.toString() ?: projectDir}/ui-lint-baseline.xml")

        val sb = StringBuilder()
        sb.append("## UI Compliance Report\n\n")

        if (!reportFile.exists()) {
            sb.append("✅ No lint report found. Assuming full compliance.\n")
        } else {
            try {
                val json = reportFile.readText()
                val gson = com.google.gson.Gson()
                val report: Map<*, *>? = gson.fromJson(json, Map::class.java)
                val issues = when (val rawIssues = report?.get("issues")) {
                    is List<*> -> rawIssues.filterIsInstance<Map<String, Any>>()
                    else -> emptyList()
                }

                val totalIssues = issues.size
                val errors = issues.count { it["severity"] == "ERROR" }
                val warnings = issues.count { it["severity"] == "WARNING" }
                val execTime = (report?.get("executionTimeMs") as? Number)?.toLong() ?: 0
                val baselineCount = if (baselineFile.exists()) {
                    baselineFile.readLines().count { it.contains("<issue") }
                } else 0

                sb.append("### Summary\n")
                sb.append("| Metric | Value |\n")
                sb.append("| :--- | :--- |\n")
                sb.append("| Total Issues Found | $totalIssues |\n")
                sb.append("| Blocking Errors | 🚨 $errors |\n")
                sb.append("| Warnings | ⚠️ $warnings |\n")
                sb.append("| Baseline Issues Ignored | $baselineCount |\n")
                sb.append("| Lint Execution Time | ${execTime}ms |\n\n")

                if (errors > 0) {
                    sb.append("### 🚨 Top 5 Blocking Errors\n")
                    sb.append("| Issue ID | File | Line | Message |\n")
                    sb.append("| :--- | :--- | :--- | :--- |\n")
                    issues.filter { it["severity"] == "ERROR" }.take(5).forEach { issue ->
                        sb.append("| ${issue["id"]} | ${issue["file"]} | ${issue["line"]} | ${issue["message"]} |\n")
                    }
                }
            } catch (e: Exception) {
                sb.append("❌ Error parsing lint report: ${e.message}\n")
            }
        }

        sb.append("\n---\n")
        sb.append("*Generated by UI Lint CI Pipeline at ${System.currentTimeMillis()}*\n")
        outputFile.writeText(sb.toString())
        println("Compliance report generated at: ${outputFile.absolutePath}")
    }
}
