package com.shadowai.app.agent

import com.shadowai.app.tasks.Plan
import com.shadowai.app.tasks.PlanNode
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Agent responsible for validating plans generated by the SupervisorAgent.
 * Implementation for Phase 6: Agentic Governance.
 *
 * The CriticAgent acts as a second "brain" that reviews proposed actions
 * against security policies and environmental consistency before execution.
 */
@Singleton
class CriticAgent @Inject constructor(
    private val verificationEngine: VerificationEngine
) {
    sealed class CriticResult {
        object Passed : CriticResult()
        data class Rejected(val reason: String, val feedback: String) : CriticResult()
    }

    /**
     * Critiques a proposed plan.
     * Checks all nodes for safety, permissions, and state consistency.
     */
    fun critiquePlan(plan: Plan, envHistory: String = ""): CriticResult {
        for (node in plan.nodes) {
            val result = validateNode(node, envHistory)
            if (result is CriticResult.Rejected) {
                return result
            }
        }
        return CriticResult.Passed
    }

    private fun validateNode(node: PlanNode, envHistory: String): CriticResult {
        // 1. Check Preconditions & Permissions
        val verification = verificationEngine.verifyAction(node.action)
        if (verification !is VerificationEngine.VerificationResult.Passed) {
            return CriticResult.Rejected(
                reason = "Precondition failed for node ${node.id}",
                feedback = when (verification) {
                    is VerificationEngine.VerificationResult.PreconditionMissing -> verification.message
                    is VerificationEngine.VerificationResult.PolicyViolation -> verification.message
                    else -> "Unknown verification failure"
                }
            )
        }

        // 2. Check Environmental Consistency (Phase 3.3 extension)
        val consistency = verificationEngine.verifyConsistency(node.action, envHistory)
        if (consistency !is VerificationEngine.VerificationResult.Passed) {
             return CriticResult.Rejected(
                reason = "Consistency violation in node ${node.id}",
                feedback = (consistency as VerificationEngine.VerificationResult.PolicyViolation).message
            )
        }

        return CriticResult.Passed
    }
}
