package com.shadowai.provideradapters

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOn
import kotlinx.coroutines.Dispatchers
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.ResponseBody
import okio.BufferedSource
import java.io.IOException

/**
 * Represents a Server-Sent Event (SSE) from a streaming response.
 */
data class SseEvent(
    val id: String? = null,
    val event: String? = null,
    val data: String = "",
    val retry: Int? = null
)

/**
 * Represents a streaming response from an AI provider.
 */
sealed class StreamingResponse {
    /**
     * A content chunk containing incremental text generated by the model.
     */
    data class Chunk(val content: String) : StreamingResponse()

    /**
     * Indicates the streaming has completed successfully.
     */
    data object Done : StreamingResponse()

    /**
     * An error occurred during streaming.
     */
    data class Error(val exception: Throwable) : StreamingResponse()
}

/**
 * Parses a single SSE line according to the SSE specification.
 *
 * SSE format details:
 * - Lines beginning with "data:" contain message data
 * - Lines beginning with "event:" define the event type
 * - Lines beginning with "id:" set the event ID
 * - Lines beginning with "retry:" set the reconnection time
 * - Empty lines trigger dispatch of the event
 *
 * @param line A single line from an SSE stream
 * @return The parsed SseEvent, or null if the line is empty/invalid
 */
fun parseSseLine(line: String): SseEvent? {
    if (line.isEmpty() || line.startsWith(":")) {
        // Empty lines are used to signal dispatch, comments are ignored
        return null
    }

    var id: String? = null
    var event: String? = null
    var data: String? = null
    var retry: Int? = null

    val fieldSeparatorIndex = line.indexOf(':')

    if (fieldSeparatorIndex == -1) {
        // No colon found - treat entire line as field name with empty value
        return null
    }

    val field = line.substring(0, fieldSeparatorIndex)
    val value = line.substring(fieldSeparatorIndex + 1).let {
        // Remove optional leading space
        if (it.startsWith(" ")) it.substring(1) else it
    }

    when (field) {
        "id" -> id = value
        "event" -> event = value
        "data" -> data = value
        "retry" -> retry = value.toIntOrNull()
        // Unknown fields are ignored per SSE spec
    }

    return if (id != null || event != null || data != null || retry != null) {
        SseEvent(id = id, event = event, data = data ?: "", retry = retry)
    } else {
        null
    }
}

/**
 * Executes a streaming HTTP request and yields parsed responses.
 *
 * This function handles:
 * - Making the HTTP request with proper headers for streaming
 * - Reading the response as a stream of SSE events
 * - Parsing each SSE line and extracting text content
 * - Emitting [StreamingResponse.Chunk] for incremental content
 * - Emitting [StreamingResponse.Done] when the stream completes
 * - Emitting [StreamingResponse.Error] for any errors
 *
 * @param httpClient The OkHttpClient to use for the request
 * @param request The pre-configured HTTP request
 * @param parser A function that extracts text content from the SSE data field
 * @return A Flow that emits streaming responses
 */
fun executeStreamingRequest(
    httpClient: OkHttpClient,
    request: Request,
    parser: (String) -> String?
): Flow<StreamingResponse> = flow {
    try {
        // Execute the request
        val response = httpClient.newCall(request).execute()

        if (!response.isSuccessful) {
            emit(
                StreamingResponse.Error(
                    IOException("HTTP error: ${response.code} - ${response.message}")
                )
            )
            return@flow
        }

        val body: ResponseBody = response.body
            ?: run {
                emit(StreamingResponse.Error(IOException("Empty response body")))
                return@flow
            }

        val source: BufferedSource = body.source()

        // Read lines from the SSE stream
        while (!source.exhausted()) {
            val line = source.readUtf8Line() ?: continue

            val sseEvent = parseSseLine(line)

            if (sseEvent?.event == "error") {
                emit(StreamingResponse.Error(IOException("SSE error event: ${sseEvent.data}")))
                continue
            }

            val content = sseEvent?.data?.let { data ->
                if (data == "[DONE]" || data.isEmpty()) {
                    null
                } else {
                    parser(data)
                }
            }

            if (content != null) {
                emit(StreamingResponse.Chunk(content))
            }
        }

        emit(StreamingResponse.Done)

    } catch (e: IOException) {
        emit(StreamingResponse.Error(e))
    } catch (e: Exception) {
        emit(StreamingResponse.Error(e))
    }
}.flowOn(Dispatchers.IO)

/**
 * Extension function to check if the provider supports streaming.
 * Adapters can override this to signal their streaming capability.
 */
fun ProviderAdapter.supportsStreaming(): Boolean {
    return this is StreamingProviderAdapter
}

/**
 * Interface for adapters that support streaming execution.
 * Implementors must provide streaming capability.
 */
interface StreamingProviderAdapter : ProviderAdapter {
    /**
     * Executes a streaming transformation.
     *
     * @param transform The transformation to perform
     * @param input The input content
     * @param parameters Additional execution parameters
     * @return A Flow of streaming responses, or null if streaming is not supported for this transform
     */
    override fun executeStreaming(
        transform: com.shadowai.core.Transform,
        input: Any,
        parameters: Map<String, Any>
    ): Flow<StreamingResponse>?
}
