ktor {
  deployment {
    port = 8081
  }
  application {
    modules = [ com.shadowai.backend.ApplicationKt.module ]
  }
}

novita {
  apiKey = ${?NOVITA_API_KEY}
  baseUrl = ${?NOVITA_BASE_URL}
  webhookSecret = ${?NOVITA_WEBHOOK_SECRET}
}

pixai {
  apiKey = ${?PIXAI_API_KEY}
  baseUrl = ${?PIXAI_BASE_URL}
  webhookSecret = ${?PIXAI_WEBHOOK_SECRET}
}

api {
  key = ${?API_KEY}
}
